Repository googleapis/java-assured-workloads, pull requests merged in 2020-09, with the labels that each got.

#4 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#5 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#15 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#16 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#21 chore: regenerate common templates
  .github/workflows/auto-release.yaml
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#23 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
