Repository googleapis/java-assured-workloads, pull requests merged in 2021-05, with the labels that each got.

#217 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: assuredworkloads, automerge, cla: yes, context: none

#218 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: assuredworkloads, automerge, cla: yes

#219 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: assuredworkloads, automerge, cla: yes, context: full

#223 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: assuredworkloads, automerge, cla: yes, context: full

#224 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: assuredworkloads, automerge, cla: yes, context: full

#226 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: assuredworkloads, automerge, cla: yes, context: full

#228 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: full
